from pathlib import Path
import time
from langchain.tools import tool
from docxtpl import DocxTemplate

@tool("generate_word_doc")
async def generate_word_doc_tool(title: str, findings: list) -> str:
    """
    Use this tool to create a professional, high-quality Word document (.docx).
    
    Args:
        title (str): The main title of the report.
        findings (list): A list of strings. IMPORTANT: Each string in this list 
                         must be a LONG, DETAILED section (250-400 words) with 
                         technical depth. Do not provide short bullets.
    
    Returns:
        str: The absolute file path to the generated document.
    """
    try:
    
        base_dir = Path(__file__).resolve().parent.parent.parent.parent
        template_path = base_dir / "app" / "templates" / "word_template.docx"
        workspace_dir = base_dir/ "project_workspace"
        

        if not template_path.exists():
            return f"Error: Template file not found at {template_path}. Please ensure the file exists."


        doc = DocxTemplate(template_path)
        

        context = {
            "title": title.upper(),
            "date": time.strftime("%B %d, %Y"),
            "findings": findings,  # This will be a list of long paragraphs
            "footer_text": "Generated by O.L.i.S.A"
        }
        

        doc.render(context)
        
        workspace_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{title.replace(' ', '_')}_{time.strftime('%d-%m-%Y')}.docx"
        output_path = workspace_dir / filename
        
        doc.save(output_path)
        
        return f"SUCCESS: Document created at {output_path}"

    except Exception as e:
        return f"Error generating document: {str(e)}"


